### ISSUE TITLE
Supports Android?

### ISSUE THREAD

**Issue by pitaslayer** [DanielArnett/SampleUnityMjpegViewer#2]
Sorry for being necromancer,

But this sample can work in Android Devices?
If it can, can you point me what is necessary for me to change?

Kind Regards,

**Comment by DanielArnett** [comment]
I haven't tested it, however there aren't really any significant
dependencies so I don't see why it wouldn't work. It's just C# opening a
network connection and receiving bytes. Think you can compile the project
as an Android project and try it?

**Comment by pitaslayer** [comment]
Yeap I did that.
But when tried in android device got this error:   Error received while reading the MJPEG.
And after debug, I found the problematic line: 

HttpWebResponse resp = (HttpWebResponse)req.EndGetResponse(asyncResult);
at line 126 of MjpegProcessor.cs

Is getting stuck there in my testing device, dont know why.

**Comment by pitaslayer** [comment]
Daniel,

It is fixed. It was a configuration in the player settings. :)

**Comment by DanielArnett** [comment]
Woah! Well done, can you share a link in case someone else stumbles on this
thread?

**Comment by pitaslayer** [comment]
Okay!

Solution for the HttpWebResponse resp = (HttpWebResponse)req.EndGetResponse(asyncResult) being hang in Android.

Open Build Settings -> Player Settings -> Android Settings -> Configuration -> Internet Access

Check if you have the Require option selected not the Auto option because in my case even with the WiFi-Connection On, it wasn't making requests.
